# Development setup
version: '3.9'

services:
  slurmctl:
    container_name: slurmctl
    image: slurm
    build:
      context: .
      dockerfile: example/Dockerfile
      target: slurm
    hostname: slurmctl
    networks:
      - clusternet
    volumes:
      - ./client:/client
      - ./example/slurm.conf:/etc/slurm.conf
      - ./example/cloudburst.ini:/etc/cloudburst/cloudburst.ini
      - ./munge:/etc/munge
  login:
    container_name: login
    image: compute
    build:
      context: .
      dockerfile: example/Dockerfile
      target: compute
    command: bash
    hostname: login
    tty: true
    privileged: true
    depends_on:
      - slurmctl
    networks:
      - clusternet
    volumes:
      - ./example/slurm.conf:/etc/slurm.conf
      - ./home:/home/user
      - ./munge:/etc/munge
  compute1:
    container_name: compute1
    image: compute
    hostname: compute1
    privileged: true
    depends_on:
      - slurmctl
    networks:
      - clusternet
    volumes:
      - ./example/slurm.conf:/etc/slurm.conf
      - ./home:/home/user
      - ./munge:/etc/munge

  backend:
    container_name: backend
    image: cloudburstserver
    build:
      context: ./server
    command: --reload
    networks:
      - clusternet
    volumes:
      - ./server:/app
      - ./example/cloudburstd.ini:/etc/cloudburst/cloudburstd.ini
      - ./example/clouds.yaml:/etc/clouds.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

networks:
  clusternet:
    name: clusternet
