# Development setup
version: '3.9'

services:
  slurmctl:
    container_name: slurmctl
    image: slurm
    build:
      context: .
      dockerfile: example/Dockerfile
      target: slurm
    hostname: slurmctl
    networks:
      - clusternet
    volumes:
      - ./example/slurm.conf:/config/slurm.conf
      - ./client:/client
      - slurmdata:/data
      - mungeconfig:/mungeconfig
  backend:
    container_name: backend
    image: cloudburstserver
    build:
      context: ./server
    command: --reload
    networks:
      - clusternet
    volumes:
      - ./server/src:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
  login:
    container_name: login
    image: compute
    build:
      context: .
      dockerfile: example/Dockerfile
      target: compute
    command: su user
    hostname: login
    tty: true
    privileged: true
    depends_on:
      - slurmctl
    networks:
      - clusternet
    volumes:
      - ./example/slurm.conf:/config/slurm.conf
      - sharedrive:/home/user
      - mungeconfig:/mungeconfig

volumes:
  mungeconfig:
  slurmdata:
  sharedrive:

networks:
  clusternet:
    name: clusternet
