#cloud-config

package_update: true
packages:
  - munge
  - slurmd
  - slurm-client
  {% if node_type == "login" %}
  - slurmctld
  {% endif %}

write_files:
  - encoding: base64
    content: {{ munge_key }}
    owner: munge:munge
    path: /etc/munge/munge.key
    permissions: "0440"
    defer: true

runcmd:
  - mkdir /var/spool/slurmctld /var/spool/slurmd
  - chown slurm:slurm /var/spool/slurmctld /var/spool/slurmd
  # MUNGE doesn't detect hostname properly unless we set it explicitly??
  # Appends entry for our hostname at the top of hostsfile
  - sudo sed -i "1s/^/127.0.1.1     {{ hostname }}\n/" /etc/hosts
